###
POST http://localhost:7071/api/HttpTrigger/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://localhost:7071/api/HttpTrigger/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "rating" : 3, 
    "userId" : "123",
    "productId" : "123", 
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###